### ISSUE TITLE
prometheus_query failing to load

### ISSUE THREAD

**Issue by sesquipedality** [lfasci/homeassistant-prometheus-query#12]
Error message as below:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:172
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:55:26 (3 occurrences)
Last logged: 21:57:03

[139782060762256] The system cannot restart because the configuration is not valid: Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0']. Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0']. Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0']. Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0']. Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0']. Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0'].
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 738, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 172, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0'].
Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0'].
Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0'].
Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0'].
Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0'].
Platform error sensor.prometheus_query - Requirements for prometheus_query not found: ['requests==2.25.0'].
```

**Comment by sesquipedality** [comment]
Further useful info from the logs:

```
2022-03-02 20:32:38 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of requests==2.25.0
2022-03-02 20:32:40 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package requests==2.25.0: ERROR: Cannot inst
all requests==2.25.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conf
licts
```

**Comment by tonobo** [comment]
Can confirm this behavior

**Comment by lfasci** [comment]
Cab you give more info about the environment ? OS, home assistant version, other error messages in log

thank you

**Comment by sesquipedality** [comment]
## System Health

version | core-2022.3.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.13.19-3-pve
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.23.0
Stage | running
Available Repositories | 1010
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 12
views | 5
mode | storage

</details>

**Comment by sesquipedality** [comment]
My best guess would be that a bump in the Python package has caused an incompatibility with the "requests" library which seems to be a pre-requisite.  I don't know enough about python to get any further.

**Comment by tonobo** [comment]
I noticed this while upgrading to latest home assistant docker container

**Comment by lucas-stauder** [comment]
I found a way to fix it:
change requirements in manifest.json to requests==2.27.1" and it works again!

**Comment by lfasci** [comment]
I confirm lucas-stauder comment fixes problem. It is related to prometheus-client, and python version.

**Comment by lfasci** [comment]
I confirm lucas-stauder comment fixes problem. It is related to prometheus-client, and python version.

**Comment by sesquipedality** [comment]
Confirmed fixed as of latest git update. Thank you.
